
samples:
    normal: 'normal.bam'
    tumor: 'tumor.bam'

reference:
    genome: "/home/sarath/reference/GRCh37/genome/human_g1k_v37_decoy.fasta"
    genome_fai: "/home/sarath/reference/GRCh37/genome/human_g1k_v37_decoy.fasta.fai"
    genome_dict: "/home/sarath/reference/GRCh37/genome/human_g1k_v37_decoy.dict"
    targets: "/home/sarath/reference/GRCh37/Twist_Target_hg19_updated.bed"

params:
    workdir: "/home/sarath/simulation/"
    singularity: "/home/sarath/containers/bamsurgeon_latest.sif"
    splitbam: false
    procs: 1
    seed: 32337
    tmpdir: 'tmp/'
    random_snv:
        count: 500
        minvaf: 0.05
        maxvaf: 0.5
        vafbeta1: 2
        vafbeta2: 2
    random_indel:
        count: 200
        minvaf: 0.05
        maxvaf: 0.5
        vafbeta1: 2
        vafbeta2: 2
        max_length: 18
    random_sv:
        count: 100
        minvaf: 0.05
        maxvaf: 0.5
        vafbeta1: 2
        vafbeta2: 2


