#! /usr/bin/env python
# syntax=python tabstop=4 expandtab

#####################################################
#  BAMSIMULATOR - TO GENERATE GOLD STANDARD
#        NORMAL/TUMOR SAMPLE FOR
#           SOMATIC VALIDATION
#
#####################################################

# import required packages
from snakemake.utils import validate


configfile: "config.yaml"
validate(config, schema= "schemas/config.schema.yaml")

# reading samples and reference files path
samples = config['samples']
reference = config['reference']
params = config['params']

if len(samples) == 1:
	params['splitbam'] = True

workdir: params['workdir']

singularity: params['singularity']

if params['splitbam']:
	include:
		'rules/split_bam.rule'
	
	samples['normal'] = "bam/Designated_normal.bam"
	samples['tumor'] = "bam/Designated_tumor.bam"

# required output
rule all:
	input:
		"bed/random_sSNV.bed",
		"bed/random_sINDEL.bed",
		"bed/random_sSV.bed",
		"bed/cnvfile.bed.gz"


include:
	"rules/gen_random_sites.rule"
include:
	"rules/add_snv.rule"
include:
	"rules/add_indel.rule"
# include:
# 	"rules/add_sv.rule"
